### PR TITLE
fix: test.sh on macOS

### PR DESCRIPTION
**Pull request by KSXGitHub**
fixes https://github.com/ada-url/rust/issues/46

Man, I hate macOS.

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by KSXGitHub** [comment]
@anonrig Do you know how to spread an array into arguments in macOS?

**Comment by anonrig** [comment]
> @anonrig Do you know how to spread an array into arguments in macOS?

Unfortunately not. Maybe @lemire?

**Comment by lemire** [comment]
A bash script under macOS (or any other OS) runs through the bash interpreter.

**Comment by KSXGitHub** [comment]
Anyway, the PR in its current form should already give a working `test.sh` even on macOS (unless macOS fails to support environment variable too, lol), so you can already use it, @anonrig.

**Comment by KSXGitHub** [comment]
> Can you give an example?

The error message here: https://github.com/ada-url/rust/issues/46

I run them just fine on my Linux machine. I don't have macOS.

**Comment by lemire** [comment]
Your bash script assumes bash 4 or better. To use arrays portably in bash, you should make sure that they are never empty.


I recommend you add version checks if you want to use specific features of bash only available more recent releases:

```bash
if ((BASH_VERSINFO[0] < 4))
then
  echo "Sorry, you need at least bash-4.0 to run this script."
  exit 1
fi
```

**Comment by KSXGitHub** [comment]
@lemire Ah, I see. I don't know if one can update Bash in macOS because I don't use it.

@anonrig Do you prefer updating your Bash or merging this PR as it is now?

**Comment by anonrig** [comment]
This doesn't work for me as well. I think we should just remove this and add it as a test somehow.

**Comment by KSXGitHub** [comment]
> This doesn't work for me as well. I think we should just remove this and add it as a test somehow.

What is the error message?

**Pull request closed without merging**
